name: flutter_application_mail
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/postempat.jpg
    - assets/images/danantaratempat.jpg
    - assets/images/kurir.jpg
    - assets/images/poslogo.png
    - assets/images/danantara.png
    - assets/images/walogo.png
    - assets/images/admin.png
    - assets/images/kurirhome.png
    - assets/images/logo.png