name: flutter_application_mail
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.5.0
  google_fonts: ^6.2.1
  provider: ^6.1.5+1
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.0
  intl: ^0.18.0
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png" # Ganti dengan path logo kamu
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/postempat.jpg
    - assets/images/danantaratempat.jpg
    - assets/images/kurir.jpg
    - assets/images/poslogo.png
    - assets/images/danantara.png
    - assets/images/walogo.png
    - assets/images/admin.png
    - assets/images/kurirhome.png
    - assets/images/logo.png
    - assets/images/qin.jpg
    - assets/images/komunikasi.png
    - assets/images/integrasi.jpg
    - assets/images/backgroundd.jpg
    - assets/images/katakata.png
    - assets/images/backgroundmail1.jpg
    - assets/images/backgroundmail2.jpg
    - assets/images/backgroundmail3.jpg
    - assets/images/backgroundmail4.jpg
    - assets/images/backgroundmail5.jpg
    - assets/images/backgroundmail6.jpg
    - assets/images/backgroundmail7.jpg
